development:
  adapter: redis
  url: redis://localhost:6379/8

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: pit_of_sadness_production
